version: '3.8'

services:
  # Service to build API Gateway image
  api-gateway-build:
    build:
      context: .
      dockerfile: ./local-test/api-gateway.Dockerfile
      target: patched
      args:
        SN_GITHUB_NPM_TOKEN: ${SN_GITHUB_NPM_TOKEN:-dummy-token}
    image: local/mark-api-gateway:pr-test
    container_name: mark-api-gateway-test
    command: ["echo", "API Gateway image built successfully"]
    profiles: ["build"]

  # Service to build API image
  api-build:
    build:
      context: .
      dockerfile: ./local-test/api.Dockerfile
      target: patched
      args:
        SN_GITHUB_NPM_TOKEN: ${SN_GITHUB_NPM_TOKEN:-dummy-token}
    image: local/mark-api:pr-test
    container_name: mark-api-test
    command: ["echo", "API image built successfully"]
    profiles: ["build"]

  # Service to build UI image
  ui-build:
    build:
      context: .
      dockerfile: ./local-test/ui.Dockerfile
      target: patched
      args:
        SN_GITHUB_NPM_TOKEN: ${SN_GITHUB_NPM_TOKEN:-dummy-token}
    image: local/mark-ui:pr-test
    container_name: mark-ui-test
    command: ["echo", "UI image built successfully"]
    profiles: ["build"]

  # Services for actually running the applications once built
  api-gateway:
    image: local/mark-api-gateway:pr-test
    ports:
      - "8080:8080"
    depends_on:
      api-gateway-build:
        condition: service_completed_successfully
    container_name: mark-api-gateway-running
    profiles: ["run"]

  api:
    image: local/mark-api:pr-test
    ports:
      - "3000:3000"
    depends_on:
      api-build:
        condition: service_completed_successfully
    container_name: mark-api-running
    profiles: ["run"]

  ui:
    image: local/mark-ui:pr-test
    ports:
      - "80:80"
    depends_on:
      ui-build:
        condition: service_completed_successfully
    container_name: mark-ui-running
    profiles: ["run"]
