{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mark.api.name" . }}-config
data:
{{- range $name, $value := .Values.api.env }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}