{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark.api.name" $ }}-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}{{ if .Values.usePgBouncer }}?pgbouncer=true{{ end }}"
  DATABASE_URL_DIRECT: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}"
{{- range $name, $value := .Values.api.secretEnv }}
  {{ $name }}: {{ $value }}
{{- end }}
{{- end }}
