{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark.ui.name" $ }}-secrets
type: Opaque
stringData:
{{- range $name, $value := .Values.ui.secretEnv }}
  {{ $name }}: {{ $value }}
{{- end }}
{{- end }}
