{{- if .Values.ltiCredentialsManager.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark.lti-credentials-manager.name" $ }}
  annotations:
    {{- include "mark.install-first.annotations" $ | nindent 4}}
type: Opaque
stringData:
  PG_USER: {{ .Values.postgres.username }}
  PG_PASSWORD: {{ .Values.postgres.password }}
{{- with .Values.ltiCredentialsManager }}
  PICARD_USER: {{ .accessKey }}
  PICARD_PASS: {{ .secretKey }}
  SECRET_KEY_BASE: {{ .secretKeyBase | quote }}
{{- end }}
{{- range $name, $value := .Values.ltiCredentialsManager.secretEnv }}
  {{ $name }}: {{ $value }}
{{- end }}
{{- end }}
