version: "3"
services:
  app:
    read_only: true
    build:
      platforms:
        - linux/amd64
      context: .
      # if you want to install @ibm-skills-network github NPM packages, uncomment this and run using op, i.e.
      # op run -- docker-compose build
      # args:
      #   SN_GITHUB_NPM_TOKEN: $GHEC_TOKEN # make sure your GHEC_TOKEN has read:packages permissions
    ports:
      - 3000:3000
    # running using docker-compose is not recommended
    # if you want to do so, you will need to provide the necessary environment variables
    # environment:
    #   ...
