{{- if .Values.apiGateway.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark.api-gateway.name" $ }}-secrets
type: Opaque
stringData:
{{- range $name, $value := .Values.apiGateway.secretEnv }}
  {{ $name }}: {{ $value }}
{{- end }}
{{- end }}
