name: Mirror repo to github.ibm.com

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to use the GitHub API to trigger a webhook event
  repository_dispatch:

jobs:
  mirror:
    uses: ibm-skills-network/.github/.github/workflows/mirror-github-ibm.yml@main
    with:
      repo_name: mark
    secrets:
      ssh_private_key: ${{ secrets.MIRROR_GITHUB_IBM_SSH_PRIVATE_KEY }}
