name: Build and Release Image

on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 5 * * *
  workflow_dispatch:
    inputs:
      suffix:
        description: Custom suffix for tag
        required: false
  repository_dispatch:

jobs:
  build_api_gateway:
    uses: ibm-skills-network/.github/.github/workflows/release.yml@main
    with:
      image: icr.io/skills-network/mark-api-gateway
      docker_file: apps/api-gateway/Dockerfile
      docker_target: patched
    secrets: inherit

  build_api:
    uses: ibm-skills-network/.github/.github/workflows/release.yml@main
    with:
      image: icr.io/skills-network/mark-api
      docker_file: apps/api/Dockerfile
      docker_target: patched
    secrets: inherit

  build_ui:
    uses: ibm-skills-network/.github/.github/workflows/release.yml@main
    with:
      image: icr.io/skills-network/mark-ui
      docker_file: apps/web/Dockerfile
      docker_target: patched
    secrets: inherit