name: Static Analysis Security Testing Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    uses: ibm-skills-network/.github/.github/workflows/static-analysis.yml@main
    secrets:
      skills-network-bot-app-id: ${{ secrets.SKILLS_NETWORK_BOT_APP_ID }}
      skills-network-bot-private-key: ${{ secrets.SKILLS_NETWORK_BOT_PRIVATE_KEY }}
      asoc-key: ${{ secrets.ASOC_KEY }}
      asoc-secret: ${{ secrets.ASOC_SECRET }}
